language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - extra-android-support
  licenses:
    - android-sdk-license-.+

before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "sources;android-27"
  - yes | sdkmanager "docs"

after_success:
  - ./gradlew dokka
  - mv kyrie/build/javadoc/style.css kyrie/build/javadoc/kyrie
  - for f in `find kyrie/build/javadoc/kyrie/ -name "*.html"`; do sed -i 's/..\/style.css/style.css/g' $f; done

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: kyrie/build/javadoc/kyrie
  on:
    branch: master
